// Maps Google Places API types to our Spanish cuisine labels
export const GOOGLE_CUISINE_MAP = {
    'japanese_restaurant': 'Japonesa',
    'italian_restaurant': 'Italiana',
    'mexican_restaurant': 'Mexicana',
    'chinese_restaurant': 'China',
    'french_restaurant': 'Francesa',
    'indian_restaurant': 'India',
    'thai_restaurant': 'Tailandesa',
    'spanish_restaurant': 'Española',
    'mediterranean_restaurant': 'Mediterránea',
    'greek_restaurant': 'Griega',
    'american_restaurant': 'Americana',
    'korean_restaurant': 'Coreana',
    'vietnamese_restaurant': 'Vietnamita',
    'seafood_restaurant': 'Marisquería',
    'vegetarian_restaurant': 'Vegetariana',
    'steak_house': 'Asador',
    'tapas_bar': 'Tapas',
    'sushi_restaurant': 'Japonesa',
    'pizza_restaurant': 'Italiana',
    'burger_restaurant': 'Americana',
    'bar': 'Tapas',
};
